### PR TITLE
Added support to install dependencies using most common package managers

### PR DESCRIPTION
**Pull request by ShalmonAnandas**
Added support to auto install dependencies using:
> pacman
> apt
> dnf
> zypper

With identifiers for most common distros:
> debian based
> arch based
> fedora
> opensuse

Sorry for crowding your pull requests. New pull request opened cause I forgot to edit out the debug step and put in the final command, oops :P

### CODE REVIEW

**Comment by alex1701c** [comment]
But there are more dependencies than the ones from the script (like Qt and KDE headers).

For my projects I have the dependencies in the README, see https://github.com/alex1701c/JetBrainsRunner/#required-dependencies

**Comment by ShalmonAnandas** [comment]
> But there are more dependencies than the ones from the script (like Qt and KDE headers).
> 
> For my projects I have the dependencies in the README, see https://github.com/alex1701c/JetBrainsRunner/#required-dependencies

All the Qt and KDE dependencies are already resolved when KDE is installed. I only added the ones that are not installed by default. I did a fresh arch install to check the required dependencies on KDE and the only ones required to be installed seperately on compile were cmake and extra-cmake-modules.

**Comment by alex1701c** [comment]
@ShalmonAnandas are you using an arch based OS? There you don't have a split between libraries and their headers, but that is not the case for the other distros.

**Comment by ShalmonAnandas** [comment]
Yeah I'm using arch. Lets just close this pull request till I get a chance to test on other distros. I still have to setup my VMs.

**Comment by santiacq** [comment]
Hi! Thanks to both of you for helping with this
I like the idea of having `install.sh` install the dependencies, however I will also list the dependencies in the readme as @alex1701c does, for documentation purposes

**Comment by Deepsvyas** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
russel-ra, @Jollyfellow1, @simonuid, @flank-code, @m10r, @taerbao, @zjhdoit, @lleifermann, @lattesir, @zanonShao, @hqman, @jhartley218, @kenandalda, @benpaodewoniu, @AlexNi245, @githublister, @AbOsmn, @nneven, @stasb, @k0dia, @dracpet, @Blaze729, @sunsided, @cupidhack, @Ants518, @0xAdamb, @Jhay327, @raphdeknop, @realChenHui, @pysh4k, @sleeyax, @Sinan-Ak, @hlhdaiaaii, @teryanarmen, @Yeoninm, @Antonito, @ryom0624, @markall93, @0xCaso, @takahiro-prog, @cucrisis, @AlgoQ, @HAOYUatHZ, @sebastiantf, @0x4a5e1e4baab, @SPIRY-RO, @hillhero789, @tsarbuig, @Jamerrred, @avgor80cylzxje, @a123465, @marketneutral, @eliaselm, @mschrader15, @denji, @YJZyjz185672, @playniuniu, @bardoga, @EricSantos00, @fkGfwNiubility, @tonydspaniard, @hoichung, @elboby, @florinnichifiriuc, @patrick-fitzgerald, @step21, @Patrollia, @zheli, @dame18dame18, @pittvailer, @Larcaster, @KuepeliAhmet, @cryptohazard, @jefflam, @alexonec, @hazelld, @0x000da38758, @raffdelfin, @BukanSuprianto, @wardbradt, @hamannju, @cjxe, @kittisak-phetrungnapha, @yumingzhe, @ReservedSnow673, @unbalancedparentheses, @savvn001, @EchoJZ, @jeffchen006, @amanusk, @colinbowen, @yuradmt, @Centori, @malzzz, @ronert2640, @rinoc, @dlc4rb-l, @Vannylol, @Mobey-eth

**Comment by Deepsvyas** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kesar, @gg2001, @markall93, @mats006, @robriks, @time0x, @raphdeknop, @afmsavage, @cipherg00n, @socrates-yxh, @TenviLi, @JupiterM, @aamargant, @crypt1d, @gabrielo123513, @jesusxy, @wk0, @ligulfzhou, @iamhenry, @bitciphr, @ghiliweld, @pacovilletard, @mayooear, @philippnagel, @Rakx00000, @phongsathorn1, @Youngshark3, @JackyCZJ, @krajarajan, @nextbcpv, @ConradSollitt, @MostafaMhmod, @zomglings, @urbanyoungv2, @marcgraczyk, @sarhaang, @bryansayler, @tintinweb, @RebornFlamme, @c-source-dev, @adamsvoboda, @LeoHChen, @kennardo, @yrao3, @jdram62, @l-henri, @siddharth9903, @beans42, @TobiasBK, @mitchellwilburnstevehubs, @0xShinji, @NerdTsai, @hmrtn, @sambarnes, @stephenjtong, @pshenkoalex, @LingchaoM, @0xpapercut, @Mudassir45, @calvinturner, @DogeTheBountyHunter, @joserochadocarmo, @kels-code, @maszangeneh, @gustom00, @robriks, @BS2911, @thedownup, @acastellana, @lilao6, @s0wcy, @climber2002, @hanhan0427, @zdietzen, @zomglings, @haiheipijuan, @edgar-orozco, @cenobyte321, @lianqiang, @mats006, @yashwantx, @kai98, @Tiresiasel, @RoamWang, @0xArsen, @hongyutx, @jesusxy, @0xrev, @rafinskipg, @maurodelazeri, @0x366, @tokyoDan67, @cipherg00n, @ameya-deshmukh, @Pxls21, @kota5115, @urbanyoungv2, @CPUFronz, @santiacq

**Pull request closed without merging**
